### Raiz da aplicação
GET http://localhost:5190

### Listar os produtos
GET http://localhost:5190/api/produto/listar

### Buscar produto por nome
GET http://localhost:5190/api/produto/buscar/Mouse

### Cadastrar produto
POST http://localhost:5190/api/produto/cadastrar
Content-Type: application/json

{
    "nome" : "Mouse",
    "quantidade" : 123,
    "preco" : 57.75
}

### remover produto por nome 
DELETE  http://localhost:5190/api/produto/delete/d76f7429-5a32-4cd7-b547-c6c57d99b87a

### alterar
DELETE http://localhost:5190//api/produto/alterar/